<?php $this->headScript()->appendFile('/js/jasny-bootstrap.min.js') ?>
<?php echo $this->headLink()->appendStylesheet('/css/jasny-bootstrap.min.css'); ?>	
<?php $this->headScript()->appendFile('/js/modules/promos/validatePromos.js') ?>

<input id="hRefLinkMain" type="hidden" value="/admin/countrys/index?strInput=<?php echo $this->dataCountry['code'];?>" />
<div class="row-fluid">
	<div class="navbar  m-top-3 no-margin-b">
    	<div class="navbar-inner">
            <ul class="breadcrumb">
                <i class="icon-chevron-left hide-sidebar"><a href="#" title="Hide Sidebar" rel="tooltip">&nbsp;</a></i>
                <i class="icon-chevron-right show-sidebar" style="display:none;"><a href="#" title="Show Sidebar" rel="tooltip">&nbsp;</a></i>
                <li>
                    <a href="/admin/admongral/index">Paises</a> <span class="divider">/</span>	
                </li>
                <li>
                    <a href="/admin/countrys/index?strInput=<?php echo $this->dataCountry['code'];?>"><?php echo $this->dataCountry['name'];?></a> <span class="divider">/</span>
                </li>	                
                <li class="active">Promociones</li>
            </ul>           
    	</div>
	</div>
</div>

<div class="row-fluid">    
	<div class="span12">
		<!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
					Información de la Promocion
				</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                	<?php if(@$this->errors['status']):?>
						<div id="divpErrorLogin" class="alert alert-error" style="display:block;">
						  <button type="button" class="close" data-dismiss="alert">√ó</button>
						  <h4>Error</h4>
						  <div>Ha ocurrido un error al insertar el registro.</div>
						</div>	                	
                	<?php endif;?>
					
					<form method="POST" action="/admin/promos/getinfo?catId=<?php echo $this->idToUpdate; ?>&codeCountry=<?php echo $this->dataCountry['code'];?> " id="FormData" class="form-horizontal"  enctype="multipart/form-data">
						<input type="hidden" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
		                <input type="hidden" id="catId" name="catId" value="<?php echo $this->idToUpdate; ?>" />
		                <input type="hidden" id="codeCountry" name="codeCountry" value="<?php echo $this->dataCountry['code'];?>" />
		                
		                <?php if($this->resultOp=='okRegister'): ?>
		                    <div class="alert alert-success">
		                        <button class="close" data-dismiss="alert"></button>
		                        Datos se almacenaron correctamente.
		                    </div>  
		                <?php endif;?>    		              
			                <fieldset>
			                	<div class="span12">
			                		<div class="span6">
										<div class="control-group">
											<label class="control-label">Producto<span class="required">*</span></label>
											<div class="controls">
												<select class="m-wrap span12" name="inputProduct" id="inputProduct" >
													<option value="">Seleccionar una opción</option>
					                                <?php echo $this->aProducts;?>
												</select>
											</div>
										</div>																					

			                		</div>
			                		<div class="span6">
										<div class="control-group">
											<label class="control-label">Nombre<span class="required">*</span></label>
											<div class="controls">
												<input type="text" name="inputName" id="inputName" class="m-wrap span12" value="<?php echo @$this->data['nombre']; ?>" >
											</div>
										</div>
			                		</div>
			                	</div>

			                	<div class="span12 formcustom">
			                		<div class="span6">
										<div class="control-group">
											<label class="control-label">Imagen</label>
											<div class="controls">
							                    <div class="fileinput fileinput-new" data-provides="fileinput">
							                      <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 165px; height: 150px;">
							                            <img height="210" src="http://test.petlocator.com.mx/assets/images/promos/<?php echo (isset($this->data['imagen']) && $this->data['imagen']!="") ? $this->data['imagen']: "no_disponible.jpg"; ?>" class="">
							                      </div>
							                      <div>
							                        <span class="btn btn-default btn-file">
							                        <span class="fileinput-new">Seleccionar Imagen</span>
							                        <span class="fileinput-exists">Cambiar</span>
							                        <input type="file" name="imageProfile"></span>
							                        <a href="#" class="btn btn-default fileinput-exists span12" data-dismiss="fileinput">Eliminar</a>
							                      </div>
							                    </div>

							                    <div class="<?php echo (isset($this->errors['errorImage'])) ? 'div-border-error': '';?>">
							                        <p class="">Formatos permitidos: .png .jpg .jpeg<br/>
							                            Tamaño máximo: 10MB
							                        </p>
							                    </div>											
											</div>
										</div>		
			                		</div>
			                		<div class="span6">
										<div class="control-group">
											<label class="control-label">Descripción</label>
											<div class="controls">
												<textarea  name="inputDesc" id="inputDesc" rows="5" class="input-xlarge textarea span12" placeholder="Descripción..."><?php echo @$this->data['descripcion']; ?></textarea>
											</div>
										</div>			                			
			                		</div>			                		
			                	</div>	

			                	<div class="span12 formcustom">
			                		<div class="span6">
										<div class="control-group">
											<label class="control-label">No. Equipos Min.<span class="required">*</span></label>
											<div class="controls">
												<input type="text" name="inputMins" data-required="1" class="span6 m-wrap" value="<?php echo @$this->data['no_equipos_min']; ?>" >
											</div>
										</div>						                			
			                		</div>
			                		<div class="span6">
										<div class="control-group">
											<label class="control-label">No. Equipos Max.<span class="required">*</span></label>
											<div class="controls">
												<input type="text" name="inputMax" data-required="1" class="span6 m-wrap" value="<?php echo @$this->data['no_equipos_max']; ?>" >
											</div>
										</div>			                			
			                		</div>
			                	</div>	

			                	<div class="span12 formcustom">
			                		<div class="span6">
										<div class="control-group">
											<label class="control-label">Periodo (Meses)<span class="required">*</span></label>
											<div class="controls">
												<input type="text" id="inputPeriodo" name="inputPeriodo" class="m-wrap" value="<?php echo (@$this->data['periodo']); ?>">	
											</div>
										</div>			                			
			                		</div>
			                		<div class="span6">								
										<div class="control-group">
											<label class="control-label">Periodo Gratis(Meses)<span class="required">*</span></label>
											<div class="controls">
												<input type="text" id="inputPerGratis" name="inputPerGratis" class="m-wrap" value="<?php echo (@$this->data['periodo_gratis']); ?>">	
											</div>
										</div>	
			                		</div>
			                	</div>	

			                	<div class="span12 formcustom">
			                		<div class="span6">						
										<div class="control-group">
											<label class="control-label">Fecha Inicio<span class="required">*</span></label>
											<div class="controls">
												<input readonly id="inputInicio" name="inputInicio" data-required="1"  type="text" class="span6 m-wrap" value="<?php echo @$this->data['fecha_inicio']; ?>">
											</div>
										</div>

			                		</div>
			                		<div class="span6">	

										<div class="control-group">
											<label class="control-label">Fecha Fin<span class="required">*</span></label>
											<div class="controls">
												<input readonly type="text" id="inputFin" name="inputFin" class="span6 m-wrap" value="<?php echo (@$this->data['fecha_fin']); ?>">	
											</div>
										</div>	

			                		</div>
			                	</div>	

			                	<div class="span12 formcustom">
			                		<div class="span6">	

										<div class="control-group">
											<label class="control-label">Descuento (%)</label>
											<div class="controls">
												<input type="text" name="inputDiscount" data-required="1" class="span6 m-wrap" value="<?php echo @$this->data['porcentaje_descuento']; ?>" >
											</div>
										</div>							
			                		</div>
			                		<div class="span6">	
										<div class="control-group">
											<label class="control-label">Estatus<span class="required">*</span></label>
											<div class="controls">
												<select class="m-wrap" name="inputEstatus" id="inputEstatus" >
													<option value="">Seleccionar una opción</option>
					                                <?php echo $this->aStatus;?>
												</select>
											</div>
										</div>
			                		</div>
			                	</div>	

								<div class="control-group">
									<label class="control-label"></label>
									<div class="controls">
									</div>
								</div>								

								<div class="form-actions">
									<button type="submit" class="btn btn-primary">Guardar</button>
									<button type="button" class="btn" onClick="javascript:backToModule()">Cancelar</button>
								</div>										
						</fieldset>							
					</form>										    
				</div>			
			</div>
		</div>
	</div>	
</div> 	