<?php $this->headScript()->appendFile('/js/modules/countrys/resume.js') ?>   
	<div class="row-fluid">
		<div class="navbar  m-top-3 no-margin-b">
	    	<div class="navbar-inner">
	            <ul class="breadcrumb span2">
	                <i class="icon-chevron-left hide-sidebar"><a href="#" title="Hide Sidebar" rel="tooltip">&nbsp;</a></i>
	                <i class="icon-chevron-right show-sidebar" style="display:none;"><a href="#" title="Show Sidebar" rel="tooltip">&nbsp;</a></i>
	                <li>
	                    <a href="/admin/admongral/index">Paises</a> <span class="divider">/</span>	
	                </li>
	                <li class="active"><?php echo $this->dataInfo['name'];?></li>
	            </ul>
		    	<div class="pull-right">
		    		<a href="/admin/admongral/moreinfo?catId=<?php echo $this->dataInfo['code']; ?>&fromOrigin=1" class="btn"><i class="icon-edit"></i></a>
		    	</div>	            
	    	</div>
		</div>
	</div>

	<div class="row-fluid">	    
            <!-- /block -->
        <div class="span12">
            <!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Banners</div>
                    <div class="pull-right">

                    </div>
                </div>
                <div class="block-content collapse in">
                    <div class="table-toolbar">
                      <div class="btn-group">
                         <a href="/admin/banners/getinfo?catId=-1&codeCountry=<?php echo $this->dataInfo['code'];?>"><button class="btn btn-success"> Agregar <i class="icon-plus icon-white"></i></button></a>
                      </div>
                    </div>                 	
                	<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable"  id="dataTable">
                        <thead>             
                            <tr>
                            	<th width="70"></th>
                                <th>Nombre</th>
                                <th>Periodo</th>
                                <th>Estatus</th>                                
                                <th width="30"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $result = '';?>
                            <?php foreach($this->aBanners as $key => $items): ?>
                                <tr>      
                                	<td><img class="span12" src="http://test.petlocator.com.mx/assets/images/banners/<?php echo $items['imagen']; ?>" ></td>             
                                    <td><?php echo $items['nombre'];?></td>
                                    <td><?php echo $items['fecha_inicio'];?> al <?php echo $items['fecha_fin'];?></td>
                                    <td><?php echo $items['ESTATUS'];?></td>		                                    
                                    <td class="text-center">
                                        <a href="/admin/banners/getinfo?catId=<?php echo $items['ID']; ?>&codeCountry=<?php echo $this->dataInfo['code'];?>">
                                            <button class="btn btn-info"> <i class="icon-info-sign icon-white"></i>
                                            </button>
                                        </a>
                                    </td>
                                </tr>
                            <?php  endforeach;?>
                        </tbody>
            		</table> 
                </div>
            </div>            
        </div>
    </div>   
	<div class="row-fluid">
        <div class="span12">
            <!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Promociones</div>
                    <div class="pull-right">

                    </div>
                </div>
                <div class="block-content collapse in">
                    <div class="table-toolbar">
                      <div class="btn-group">
                         <a href="/main/users/getinfo?catId=-1"><button class="btn btn-success"> Agregar <i class="icon-plus icon-white"></i></button></a>
                      </div>
                    </div>                 	
                	<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable"  id="dataTable">
                        <thead>             
                            <tr>
                            	<th width="70"></th>
                                <th>Nombre</th>
                                <th>Descripcion</th>
                                <th>Contacto</th>
                                <th>Estatus</th>                                
                                <th width="30"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $result = '';?>
                            <?php foreach($this->aPromos as $key => $items): ?>
                                <tr>   
                                	<td><img class="span12" src="http://test.petlocator.com.mx/assets/images/promos/<?php echo $items['imagen']; ?>" ></td>                             
                                    <td><?php echo $items['nombre'];?></td>
                                    <td><?php echo $items['descripcion'];?></td>
                                    <td><?php echo $items['fecha_inicio'];?> al <?php echo $items['fecha_fin'];?></td>
                                    <td><?php echo $items['ESTATUS'];?></td>		                                    
                                    <td class="text-center">
                                        <a href="/atn/services/exportsearch?strInput=<?php echo $items['ID']; ?>">
                                            <button class="btn btn-info"> <i class="icon-info-sign icon-white"></i>
                                            </button>
                                        </a>
                                    </td>
                                </tr>
                            <?php  endforeach;?>
                        </tbody>
            		</table> 
                </div>
            </div>
		</div>   
	</div>       
	<div class="row-fluid">
        <div class="span12">
            <!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Distribuidores</div>
                    <div class="pull-right">

                    </div>
                </div>
                <div class="block-content collapse in">
                    <div class="table-toolbar">
                      <div class="btn-group">
                         <a href="/main/users/getinfo?catId=-1"><button class="btn btn-success"> Agregar <i class="icon-plus icon-white"></i></button></a>
                      </div>
                    </div> 
                	<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable"  id="dataTable">
                        <thead>             
                            <tr>
                                <th>Nombre</th>
                                <th>Ubicacion</th>
                                <th>Contacto</th>
                                <th>Estatus</th>                                
                                <th width="30"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $result = '';?>
                            <?php foreach($this->aDistribuidores as $key => $items): ?>
                                <tr>                   
                                    <td><?php echo $items['nombre'];?></td>
                                    <td><?php echo $items['LUGAR'];?></td>
                                    <td><?php echo $items['contacto'];?></td>
                                    <td><?php echo $items['ESTATUS'];?></td>		                                    
                                    <td class="text-center">
                                        <a href="/atn/services/exportsearch?strInput=<?php echo $items['ID']; ?>">
                                            <button class="btn btn-info"> <i class="icon-info-sign  icon-white"></i>
                                            </button>
                                        </a>
                                    </td>
                                </tr>
                            <?php  endforeach;?>
                        </tbody>
            		</table> 
                </div>
            </div>
            <!-- /block -->
        </div>
    </div>
    <!--
    <div class="row-fluid">
        <div class="span12">
            
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Clientes</div>
                    <div class="pull-right">

                    </div>
                </div>
                <div class="block-content collapse in">
                    <div class="table-toolbar">
                      <div class="btn-group">
                         <a href="/main/users/getinfo?catId=-1"><button class="btn btn-success"> Agregar <i class="icon-plus icon-white"></i></button></a>
                      </div>
                    </div>                 	
                	<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable"  id="dataTable">
                        <thead>             
                            <tr>
                                <th>Nombre</th>
                                <th>Pais</th>
                                <th>Distribuidor</th>
                                <th>Usuario</th>
                                <th>Ult. Acceso</th>
                                <th>No. SAP</th>				                                
                                <th width="30"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $result = '';?>
                            <?php foreach($this->aClientes as $key => $items): ?>
                                <tr>                   
                                    <td><?php echo $items['NOMBRE'];?></td>
                                    <td><?php echo $items['PAIS'];?></td>
                                    <td><?php echo $items['NDISTRIBUIDOR'];?></td>
                                    <td><?php echo $items['clt_email'];?></td>
                                    <td><?php echo $items['clt_fecha_acceso'];?></td>
                                    <td><?php echo $items['clt_sap_cardcode'];?></td>				                                    
                                    <td class="text-center">
                                        <a href="/atn/services/exportsearch?strInput=<?php echo $items['ID']; ?>">
                                            <button class="btn btn-info"> <i class="icon-info-sign icon-white"></i>
                                            </button>
                                        </a>
                                    </td>
                                </tr>
                            <?php  endforeach;?>
                        </tbody>
            		</table>   
                </div>
            </div>         
        </div>

    </div>                        -->