      <div class="row-fluid">
		<div class="span12">			
        	<div class="block row-min-h">
    		    <div class="col-md-12 text-center">
			        <h3>La venta se ha guardado correctamente..</h3>
			        <button type="button" onclick="location.href='/distribuitor/sales/index'" class="btn btn-large btn-primary">Nueva Venta</button>    		    	
    		    </div>
        	</div>
    	</div>
	</div>    