<?php $this->headScript()->appendFile('/js/modules/sales/validatePets.js') ?>   
<?php $arResume = Array();?>
<div class="row-fluid">
    <div class="navbar  m-top-3 no-margin-b">
        <div class="navbar-inner">
            <ul class="breadcrumb">
                <i class="icon-chevron-left hide-sidebar"><a href="#" title="Hide Sidebar" rel="tooltip">&nbsp;</a></i>
                <i class="icon-chevron-right show-sidebar" style="display:none;"><a href="#" title="Show Sidebar" rel="tooltip">&nbsp;</a></i>
                <li>
                    <a href="/distribuitor/sales/index">Modulo de Ventas</a> <span class="divider">/</span>  
                </li>
                <li>
                    <a href="/distribuitor/sales/products">Productos</a> <span class="divider">/</span>
                </li>
                <li>
                    Trackers
                </li>                
            </ul>           
        </div>
    </div>
</div>

<div class="row-fluid">
	<div class="span12">
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Seleccionar los trackers a utilizar.</div>
            </div>
            <div class="block-content collapse in">
                <div id="divpError" class="alert alert-error" style="display:none;">
                  <!--<button type="button" class="close" data-dismiss="alert">x</button>-->
                  <h4>Error</h4>
                  <div>Debe de seleccionar un IMEI para cada tracker.</div>
                </div>  
                <div id="divpErrorDouble" class="alert alert-error" style="display:none;">
                  <!--<button type="button" class="close" data-dismiss="alert">x</button>-->
                  <h4>Error</h4>
                  <div>Solo se puede usar un IMEI por Tracker.</div>
                </div>                                    
                <form method="POST" action="/distribuitor/sales/pets" id="FormData" class="form-horizontal ">
                    <input type="hidden" name="optReg" value="step3" />
                    <input type="hidden" id="inputTotal"  name="inputTotal" value="<?php echo $this->iCounts;?>" />
                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered"  id="dataTable">
                        <thead>             
                            <tr>
                                <th>Producto</th>
                                <th>IMEI</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $result = '';?>
                            <?php foreach($this->aProducts as $key => $items): ?>
                                <tr>
                                    <td><?php echo $items['data']['prod_titulo'];?></td>
                                    <td>
                                        <select name="selectCant<?php echo $items['id'];?>" id="selectCant<?php echo $items['id'];?>" class="span12 selectDbo" onChange="changeCbo(this.value)" >
                                            <option value="">Seleccionar una opción</option>
                                            <?php echo $this->aTrackers;?>
                                        </select>
                                    </td>  
                                </tr>          
                            <?php  endforeach;?>                         
                        </tbody>
                    </table>

                    <div class="control-group">                            
                        <div class="controls">
                        
                        </div>
                    </div> 

                    <div class="form-actions">
                        <button type="button" onClick="sendDataProducts()" class="btn btn-primary  pull-right margin-left5">Continuar <i class="icon-arrow-right icon-white"></i>

                        </button>
                        <a class="btn pull-right" href="/distribuitor/sales/cancel">
                            Cancelar
                        </a>                                
                    </div>                                      
                    </fieldset>                         
                </form>                 

            </div>
        </div>
        <!-- /block -->
    </div>
</div>   