<?php $this->headScript()->appendFile('/js/modules/admongral/validateCountrys.js') ?>   
<?php $this->headScript()->appendFile('/js/modules/functionGral.js') ?> 
<?php $disabled = 'true';?> 
<div class="row panel-data">
    <input id="hRefLinkMain" type="hidden" value="<?php echo (isset($this->dataIn['fromOrigin']) && $this->dataIn['fromOrigin']==1) ? '/admin/countrys/index?strInput='.$this->idToUpdate : '/admin/admongral/index';?>" />
	<div class="span12">
		<!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
					<a href="javascript:backToModule()">
						<i class="icon-circle-arrow-left fa-1"></i></a> Información del Pais</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                	<?php if(@$this->errors['status']):?>
						<div id="divpErrorLogin" class="alert alert-error" style="display:block;">
						  <button type="button" class="close" data-dismiss="alert">√ó</button>
						  <h4>Error</h4>
						  <div>Ha ocurrido un error al insertar el registro.</div>
						</div>	                	
                	<?php endif;?>
					
					<form method="POST" action="/admin/admongral/moreinfo" id="FormData" class="form-horizontal ">
		                <input type="hidden" name="optReg" value="update" />
		                <input type="hidden" id="catId" name="catId" value="<?php echo $this->idToUpdate; ?>" />
		                
		                <?php if($this->resultOp=='okRegister'): ?>
		                    <div class="alert alert-success">
		                        <button class="close" data-dismiss="alert"></button>
		                        Datos se almacenaron correctamente.
		                    </div>  
		                <?php endif;?>    		              
			                <fieldset>
								<div class="control-group">
									<label class="control-label">Pais<span class="required">*</span></label>
									<div class="controls">
										<select class="m-wrap" name="inputPais" id="inputPais" onChange="onChangeCountry(this.value)" <?php echo (isset($this->idToUpdate) && $this->idToUpdate=="-1") ? '': 'disabled';?>>
											<option value="">Seleccionar una opción</option>
			                                <?php echo $this->aPaises;?>
										</select>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">Clave<span class="required">*</span></label>
									<div class="controls">
										<input type="text" id="txtClave" class="span6 m-wrap" value="<?php echo @$this->data['code']; ?>" disabled >
									</div>
								</div>
								
								<div class="control-group">
									<label class="control-label">Latitud</label>
									<div class="controls">
										<input name="inputLatitud" type="text" class="span6 m-wrap" value="<?php echo @$this->data['latitude']; ?>" <?php echo $disabled;?> >
									</div>
								</div>		

								<div class="control-group">
									<label class="control-label">Longitud</label>
									<div class="controls">
										<input type="text" name="inputLongitud" data-required="1" class="span6 m-wrap" value="<?php echo @$this->data['longitude']; ?>"  <?php echo $disabled;?> >
									</div>
								</div>									

								<div class="control-group">
									<label class="control-label">Divisa<span class="required">*</span></label>
									<div class="controls">
										<input name="inputDivisa" type="text" class="span6 m-wrap" value="<?php echo @$this->data['divisa']; ?>" <?php echo $disabled;?> >
									</div>
								</div>

								<div class="control-group">
									<label class="control-label">Texto Divisa<span class="required">*</span></label>
									<div class="controls">
										<input name="inputTextDivisa" type="text" class="span6 m-wrap" value="<?php echo @$this->data['texto_divisa']; ?>" <?php echo $disabled;?> >
									</div>
								</div>

								<div class="control-group">
									<label class="control-label">Diferencia Horario<span class="required">*</span></label>
									<div class="controls">
										<input name="inputDiferencia" type="text" class="span6 m-wrap" value="<?php echo @$this->data['diferencia_horario']; ?>" <?php echo $disabled;?> >
									</div>
								</div>																			

								<div class="control-group">
									<label class="control-label">Estatus<span class="required">*</span></label>
									<div class="controls">
										<select class="m-wrap" name="inputEstatus" id="inputEstatus" <?php echo $disabled;?> >
											<option value="">Seleccionar una opción</option>
			                                <?php echo $this->aStatus;?>
										</select>
									</div>
								</div>
								
								<div class="form-actions">
									<button type="submit" class="btn btn-primary">Guardar</button>
									<button type="button" class="btn" onClick="javascript:backToModule()">Cancelar</button>
								</div>										
						</fieldset>							
					</form>										    
				</div>			
			</div>
		</div>
	</div>	
</div> 