<?php $this->headLink()->appendStylesheet('/libs/charts/styles/Attributes/jchartfx.attributes.css') ?>
<?php $this->headLink()->appendStylesheet('/libs/charts/styles/Attributes/jchartfx.palette.css') ?>
<?php $this->headScript()->appendFile('/js/modules/gralTables.js') ?>   
<?php $this->headScript()->appendFile('/libs/charts/js/jchartfx.system.js') ?>   
<?php $this->headScript()->appendFile('/libs/charts/js/jchartfx.coreVector.js') ?>   
<?php $this->headScript()->appendFile('/libs/charts/js/jchartfx.data.js') ?>   
<?php $this->headScript()->appendFile('/libs/charts/js/jchartfx.animation.js') ?>   
<?php $this->headScript()->appendFile('/libs/charts/js/jchartfx.coreVector3d.js') ?>   
<?php $this->headScript()->appendFile('/js/reports/reportsEquipments.js') ?>     
<?php $arResume = Array();?>
<div class="row panel-data">
    <div class="span12">
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Resumen de Equipos</div>
            </div> 
            <div class="block-content collapse in">
                <div class="chartcontainer">                
                    <div id='divGrafica' style='width:100%;height:300px;'></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row panel-data">
	<div class="span12">
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Equipos</div>             
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                <div class="table-toolbar">
                  <div class="btn-group">
                     <a href="/reports/equipments/moreinfo?catId=-1"><button class="btn btn-success"> Agregar <i class="icon-plus icon-white"></i></button></a>
                  </div>
                </div>                         
 					<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered"  id="dataTable">
                        <thead>             
                            <tr>
                                <th>Pais</th>                                
                                <th>Distribuidor</th>
                                <th>IMEI</th>
                                <th>Estatus</th>
                                <th>Mascota</th>
                                <th>Estatus Mascota</th>
                                <th>U. Reporte</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $result = '';?>
                            <?php foreach($this->aResume as $key => $items): ?>
                                <tr> 
                                    <td> <img style="width:25px" src="/images/banderas/<?php echo $items['bandera'];?>"/></td>
                                    <td><?php echo $items['N_DISTRIBUIDOR'];?></td>
                                    <td><?php echo $items['gpsTrackerIMEI'];?></td>                                    
                                    <td><?php echo $items['ESTATUS'];?></td>
                                    <td><?php echo $items['MASCOTA'];?></td>
                                    <td><?php echo $items['ESTATUS_MASCOTA'];?></td>
                                    <td><?php echo $items['U_REPORTE'];?></td>
                                    <td class="text-center">
                                            <a href="/reports/equipments/moreinfo?catId=<?php echo $items['gpsTrackerID']; ?>">
                                            <button class="btn"> <i class="icon-eye-open "></i>
                                            </button>
                                        </a>
                                    </td>
                                </tr> 
                                <?php if(isset($items['ASIGNADO']) && $items['ASIGNADO'] == 'Sin Asignar'):?>
                                    <?php @$arResume['NoAsignar']++;?>
                                <?php elseif(isset($items['U_REPORTE'])):?>
                                    <?php @$arResume['Reportando']++;?>
                                <?php elseif(isset($items['ASIGNADO']) && $items['ASIGNADO'] == 'Asignado' && !isset($items['U_REPORTE'])):?>
                                    <?php @$arResume['Asignado']++;?>
                                <?php endif;?>                                
                            <?php  endforeach;?>
                        </tbody>
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
</div>   
<script type="text/javascript">
    var aDataEquipos = [
            {   "Status": 'Reportando', 
                "Region" : "Total", 
                "Usage"  : <?php echo isset($arResume['Reportando']) ? $arResume['Reportando']: 0 ;?>
            },
            {   "Status" : 'Asignado Sin Reportar', 
                "Region" : "Total", 
                "Usage"  : <?php echo isset($arResume['Reportando']) ? $arResume['Asignado']: 0 ;?>
            },
            {   "Status" : 'Sin Asignar', 
                "Region" : "Total", 
                "Usage"  : <?php echo isset($arResume['NoAsignar']) ? $arResume['NoAsignar']: 0 ;?>
            },                        
    ];                                      
</script> 
