<?php $this->headScript()->appendFile('/js/modules/functionGral.js') ?>  
<?php $this->headScript()->appendFile('/js/modules/dealers/validateDealers.js') ?>

<input id="hRefLinkMain" type="hidden" value="/distribuitor/main/index?catId=<?php echo $this->data['id_distribuidor']; ?>&codeCountry=<?php echo $this->dataCountry['code'];?>"/>
<div class="row-fluid">
    <div class="navbar  m-top-3 no-margin-b">
        <div class="navbar-inner">
            <ul class="breadcrumb">
                <i class="icon-chevron-left hide-sidebar"><a href="#" title="Hide Sidebar" rel="tooltip">&nbsp;</a></i>
                <i class="icon-chevron-right show-sidebar" style="display:none;"><a href="#" title="Show Sidebar" rel="tooltip">&nbsp;</a></i>

                <?php if(@$this->dataUser['adm_tipo']==1) :?>
                    <li>
                        <a href="/admin/admongral/index">Paises</a> <span class="divider">/</span>  
                    </li>
                    <li>
                        <a href="/admin/countrys/index?catId=<?php echo $this->dataCountry['code'];?>"><?php echo $this->dataCountry['name'];?></a> <span class="divider">/</span>    
                    </li>                   
                    <li>
                        <a href="/distribuitor/main/index?catId=<?php echo $this->dataDist['id_distribuidor']; ?>&codeCountry=<?php echo $this->dataCountry['code'];?>"><?php echo $this->dataDist['nombre'];?></a> <span class="divider">/</span>
                    </li>
                <?php endif;?>
                <li>
                    Cliente
                </li>
            </ul>           
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left"> Información del Cliente</div>
            </div>
            <div class="block-content collapse in">
                     <form method="POST" action="/distribuitor/main/getinfo" id="FormData" class="form-horizontal ">
                        <input type="hidden" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
                        <input type="hidden" id="catId" name="catId" value="<?php echo $this->catId; ?>" />
                        

                        <?php if($this->resultOp=='okRegister'): ?>
                            <div class="alert alert-success">
                                <button class="close" data-dismiss="alert"></button>
                                Datos se almacenaron correctamente.
                            </div>  
                        <?php endif;?>
                        <fieldset>
                            <div class="span12 formcustom">
                                <div class="span6">
                                    <div class="control-group">
                                        <label class="control-label"><b>Nombre</b></label>
                                        <div class="controls">
                                            <label class="control-label text-left">
                                                <?php echo $this->data['clt_nombre']." ".$this->data['clt_apellidos'];?>
                                            </label>                                            
                                        </div>
                                    </div>      
                                </div>
                                <div class="span6">
                                    <div class="control-group">
                                        <label class="control-label"><b>Ult. Acceso</b></label>
                                        <div class="controls">
                                            <label class="control-label text-left">
                                                <?php echo $this->data['clt_accesos'];?>
                                            </label>                                            
                                        </div>
                                    </div>      
                                </div>
                            </div>  

                            <div class="span12 formcustom">
                                <div class="span6">
                                    <div class="control-group">
                                        <label class="control-label"><b>Usuario</b></label>
                                        <div class="controls">
                                            <label class="control-label text-left">
                                                <?php echo $this->data['clt_email'];?>
                                            </label>                                            
                                        </div>
                                    </div>      
                                </div>
                                <div class="span6">
                                    <div class="control-group">
                                        <label class="control-label"><b>Contraseña</b></label>
                                        <div class="controls">
                                            <label class="control-label text-left">
                                                <?php echo $this->data['clt_clave'];?>
                                            </label>                                            
                                        </div>
                                    </div>      
                                </div>
                            </div>                                
                            <!--
                                <div class="span12 formcustom">
                                    <div class="span4">
                                        <div class="control-group">
                                            <label class="control-label">Nombre<span class="required">*</span></label>
                                            <div class="controls">
                                                <input type="text" class="span12" readonly disabled value="<?php echo $this->data['clt_nombre']." ".$this->data['clt_apellidos'];?>"/>
                                            </div>
                                        </div>      
                                    </div>
                                    <div class="span4">
                                        <div class="control-group">
                                            <label class="control-label">Usuario<span class="required">*</span></label>
                                            <div class="controls">
                                                <input type="text" class="span12" readonly disabled value="<?php echo $this->data['clt_email'];?>"/>
                                            </div>
                                        </div> 
                                    </div>
                                    <div class="span4">
                                        <div class="control-group">
                                            <label class="control-label">Contraseña<span class="required">*</span></label>
                                            <div class="controls">
                                                <input type="text" class="span12" readonly disabled value="<?php echo $this->data['clt_clave'];?>"/>
                                            </div>
                                        </div> 
                                    </div>                                    
                                </div>
                            -->

                                <div class="control-group">
                                   
                                    <div class="controls">
                                    
                                    </div>
                                </div>                                 
                        </fieldset>                         
                    </form>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Mascotas</div>
            </div>
            <div class="block-content collapse in">
                <?php foreach($this->aPets as $key => $items):?>
                    <div class="span3 text-center">
                        <a href="javascript:void(0);" class="thumbnail">
                            <img data-src="http://test.petlocator.com.mx/images/mascotas/<?php echo $items['masc_foto'];?>" alt="260x180" style="width: 260px; height: 180px;" src="http://test.petlocator.com.mx/images/mascotas/<?php echo $items['masc_foto'];?>">                        
                            <span class="span12 <?php echo ($items['M_ESTATUS']=='Activo') ? 'tittlePet': 'tittlePetdact';?>" ><?php echo $items['masc_nombre'];?> - <?php echo $items['M_ESTATUS'];?><br/>                                
                            <div class="txtLocation">
                                <?php echo $items['dateTime'];?> <br/>
                                <?php echo $items['location'];?>
                            </div>                                                             
                            </span>    
                           <form method="POST" action="/distribuitor/clients/moreinfo?catId=<?php echo $this->catId; ?>&codeCountry=<?php echo $this->dataCountry['code'];?>&codeDist=<?php echo $this->dataDist['id_distribuidor']; ?>">
                                <input type="hidden" name="petID"     value="<?php echo $items['masc_id']; ?>"/>
                                <input type="hidden" name="petStatus" value="<?php echo ($items['M_ESTATUS']=='Activo') ? '0': '1';?>"/>
                                <input type="hidden" name="optReg"    value="changeStatus" />
                                <button type="submit" class="m-top-1 btn <?php echo ($items['M_ESTATUS']=='Activo') ? 'btn-warning': 'btn-success';?>">
                                     <?php echo ($items['M_ESTATUS']=='Activo') ? 'Desactivar': 'Activar';?>
                                </button>
                            </form>                               
                        </a>
                    </div>
                <?php endforeach;?>                
            </div>
        </div>    
    </div>
</div>